/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.64
 * Generated at: 2021-06-05 06:16:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class agent_005fhome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>HOME PAGE</title>\r\n");
      out.write("\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  \r\n");
      out.write("\t   <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("\t  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("\t  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\r\n");
      out.write("\t  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Shrikhand&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<!-- animations -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\tbody \r\n");
      out.write("\t{\r\n");
      out.write("\tbackground-color:silver;\r\n");
      out.write("\tbackground-image:linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)),url(\"images/img_bg_1.jpg\");\r\n");
      out.write("\tbackground-repeat : no-repeat;\r\n");
      out.write("\tbackground-size:1370px 950px;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\tnav\r\n");
      out.write("\t{\r\n");
      out.write("\t\tbackground-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5));\t\r\n");
      out.write("\t\tborder-bottom: 1px solid grey;\r\n");
      out.write("\t\tpadding:10px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tli\r\n");
      out.write("\t{\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\tfont-weight:bold;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tli:hover\r\n");
      out.write("\t{\r\n");
      out.write("\t\tcursor:pointer;\r\n");
      out.write("\t\tcolor:orange;\r\n");
      out.write("\t}\r\n");
      out.write("\ta:hover\r\n");
      out.write("\t{\r\n");
      out.write("\t\tcursor:pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction fu(){\r\n");
      out.write("\t\tvar d = document.LoginForm.deltime.value;\r\n");
      out.write("\r\n");
      out.write("\t\tif(d.length<0) \r\n");
      out.write("\t\t{\r\n");
      out.write("\t\talert(\"Add delivery time\");\r\n");
      out.write("\t\t            document.LoginForm.deltime.focus();\r\n");
      out.write("\t\t            document.LoginForm.deltime.value=\"\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction orp()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.getElementById(\"orph\").style.display=\"block\";\r\n");
      out.write("\t\tdocument.getElementById(\"orph1\").style.display=\"none\";\r\n");
      out.write("\t\tdocument.getElementById(\"list\").style.color=\"orange\";\r\n");
      out.write("\t\tdocument.getElementById(\"list2\").style.color=\"white\";\r\n");
      out.write("\t\tdocument.getElementById(\"completed\").style.display=\"none\";\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction comp()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.getElementById(\"orph\").style.display=\"none\";\r\n");
      out.write("\t\tdocument.getElementById(\"orph1\").style.display=\"none\";\r\n");
      out.write("\t\tdocument.getElementById(\"list\").style.color=\"orange\";\r\n");
      out.write("\t\tdocument.getElementById(\"list2\").style.color=\"white\";\r\n");
      out.write("\t\tdocument.getElementById(\"completed\").style.display=\"block\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

String area=session.getAttribute("area").toString();
String mob=session.getAttribute("mob").toString();
String un=session.getAttribute("uname").toString();

String aname=session.getAttribute("aname").toString();
String gender=session.getAttribute("gender").toString();


      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-md navbar-dark  fixed-top\">\r\n");
      out.write("\t<div class=\"container\" >\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<div >\r\n");
      out.write("\t\t\t\t<span style=\"font-family: 'Shrikhand', cursive; font-size:30px;\" class=\"navbar-brand \">");
out.println("hello ! "+aname);
      out.write("</span>\r\n");
      out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#go\">\r\n");
      out.write("\t\t\t    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t </button>\r\n");
      out.write("\t\t</div>\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\" collapse navbar-collapse \" id=\"go\">\r\n");
      out.write("\t\t\t<div class=\"ml-auto\">\r\n");
      out.write("\t\t\t<ul class=\"navbar-nav\">\r\n");
      out.write("\t\t\t\t<a href=\"agent_home.jsp\" class=\" nav-link \"  ><li id=\"list2\" class=\"nav-item \" style=\"color:orange;\">HOME</li></a>\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"dropdown \" >\r\n");
      out.write("\t\t\t\t\t\t<a class=\" nav-link\"><li class=\"nav-item dropdown-toggle\" id=\"list\" data-toggle=\"dropdown\" data-target=\"#down2\"><span class=\"caret\">VIEW</span></li></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"dropdown-menu\" id=\"down2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"dropdown-item \" onclick=\"comp()\"><b>Completed Requests</b></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"dropdown-item\"  href=\"agent_status.jsp\"><b>View All food status</b></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"dropdown-item \" onclick=\"orp()\"><b>View OrphanHomes</b></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<a href=\"help.jsp\" class=\" nav-link\" target=\"_blank\"><li class=\"nav-item \">HELP</li></a>\r\n");
      out.write("\t\t\t\t<a href=\"about.html\" class=\" nav-link\"><li class=\"nav-item \">ABOUT</li></a>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\t\t\t\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\t<a href=\"agent_login.jsp\"> <button class=\"btn btn-info btn-sm\"> LOGOUT</button></a>\r\n");
      out.write("\t\t\t\r\n");
      out.write("</nav><br><br>\r\n");
      out.write("<br><br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\" id=\"orph1\">\r\n");
      out.write("<h3 align=\"left\" style=\"font-family: 'Kaushan Script', cursive; font-size:30px; color:Yellow;\"><b>Food Requests</b></h3>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t");

		Class.forName("com.mysql.jdbc.Driver");
		
		Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/food","root","");
				
		Statement st=con.createStatement();
		
		ResultSet rs=st.executeQuery("select * from food_details where area='"+area+"' and Status='SENT TO AGENT' ");

	

	if(request.getParameter("id1")!=null)
	{

      out.write("\t\t\r\n");
      out.write("\t\t<h5><i><font color=\"red\">Sorry! This request is accepted by another agent,<br>Try for another if you have</font></i></h5>\r\n");
	
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<table class=\"table table-secondary table-responsive\">\r\n");
      out.write("\t\t<thead class=\"thead-dark \">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<th>Food_Requested Date (YY-MM-DD) &nbsp &nbsp</th>\r\n");
      out.write("\t\t\t\t\t\t<th>donar_name  &nbsp &nbsp</th> \r\n");
      out.write("\t\t\t\t\t\t<th>Food_Requested address &nbsp &nbsp</th>\r\n");
      out.write("\t\t\t\t\t\t<th>donar_mobile &nbsp &nbsp</th>\r\n");
      out.write("\t\t\t\t\t\t<th> pickuptime &nbsp &nbsp</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Orphange Area  &nbsp &nbsp</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Status_Of_Request &nbsp &nbsp</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Acceptance &nbsp &nbsp</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Rejection &nbsp &nbsp</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Accepted_Agent name &nbsp &nbsp</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Accepted_Agent mobile &nbsp &nbsp </th>\r\n");
      out.write("\t\t\t\t\t\t<th>DELIVERED_STATUS &nbsp &nbsp</th>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t<th></th>\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t\t\t");

			
			while(rs.next() )
			{
			
				String j=rs.getString(10) ;
				String a=rs.getString(1) ;
				String f=rs.getString(6) ;
				String h=rs.getString(8) ;
				String c=rs.getString(3) ;
				String g=rs.getString(7) ;
				String k=rs.getString(11) ;
				String l=rs.getString(12);
				String m=rs.getString(13);
				
				
				
			
			
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(j );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(a );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(f );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(h );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(c );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(g );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td><font color=\"green\"><b>");
      out.print(k );
      out.write("</b></font></td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td><a href=\"accept.jsp?dname=");
      out.print(a);
      out.write("&area=");
      out.print(area);
      out.write("&dt=");
      out.print(h);
      out.write("&mob=");
      out.print(mob);
      out.write("&aname=");
      out.print(aname);
      out.write("\"><button class=\"btn btn-success btn-block btn-sm\">Accept</button></a></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"reject.jsp?id=");
      out.print(a );
      out.write("\"><button class=\"btn btn-danger btn-block btn-sm\">reject</button></a></td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(l );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(m );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"completed.jsp?id=");
      out.print(a);
      out.write("&area=");
      out.print(g);
      out.write("&dt=");
      out.print(j);
      out.write("\"><button class=\"btn btn-success btn-block btn-sm\"> Delivered</button></a></td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
			

		}

      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("<!--  \r\n");
      out.write("<form name=\"LoginForm\" onSubmit=\"return fu();\" action=\"delivery_time.jsp?dname\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("<tr>\r\n");
      out.write("<th style=\"font-family: 'Kaushan Script', cursive; font-size:30px; color:Yellow;\">Delivery Time</th>\r\n");
      out.write("<td><input type=\"text\" name=\"deltime\" pattern=\"(([1]?[0-9])([AaPp][Mm]))|(([[0-9])([AaPp][Mm]))\" title= \"enter Am or Pm\"><input type=\"submit\" value=\"save\" > </td>\t\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<br><br>-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 2nd table -->\t<!-- 2nd table -->\t<!-- 2nd table --> \t<!-- 2nd table -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

					
			Statement st1=con.createStatement();

			ResultSet rs1=st1.executeQuery("select * from food_details where area='"+area+"' and Status='ACCEPTED' and agent_name='"+aname+"' ");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");


			
			while(rs1.next() )
			{
			
				String j=rs1.getString(10) ;
				String a=rs1.getString(1) ;
				String f=rs1.getString(6) ;
				String h=rs1.getString(8) ;
				String c=rs1.getString(3) ;
				String g=rs1.getString(7) ;
				String k=rs1.getString(11) ;
				String l=rs1.getString(12);
				String m=rs1.getString(13);
				
			
			
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(j );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(a );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(f );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(h );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(c );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(g );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td><font color=\"green\"><b>");
      out.print(k );
      out.write("</b></font></td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td><a href=\"accept.jsp?dname=");
      out.print(a);
      out.write("&area=");
      out.print(area);
      out.write("&dt=");
      out.print(h);
      out.write("&mob=");
      out.print(mob);
      out.write("&aname=");
      out.print(aname);
      out.write("\"><button class=\"btn btn-success btn-block btn-sm\">Accept</button></a></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"reject.jsp?id=");
      out.print(a );
      out.write("\"><button class=\"btn btn-danger btn-block btn-sm\">reject</button></a></td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(l );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(m );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"completed.jsp?id=");
      out.print(a);
      out.write("&area=");
      out.print(g);
      out.write("&dt=");
      out.print(j);
      out.write("\"><button class=\"btn btn-success btn-block btn-sm\"> Delivered</button></a></td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 3nd table -->\t<!-- 3nd table -->\t<!-- 3nd table --> \t<!-- 3nd table -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\" id=\"orph\" style=\"display:none;\">\r\n");
      out.write("<h3 align=\"left\" style=\"font-family: 'Kaushan Script', cursive; font-size:30px; color:Yellow;\"><b>Orphan homes list</b></h3>\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"col-lg-12\">\r\n");
      out.write("\t<table class=\"table table-secondary \">\r\n");
      out.write("\t");

		
	Statement st2=con.createStatement();
	
	ResultSet rs2=st2.executeQuery("select * from  add_orphan ");
			
	/*		PreparedStatement ps=con.prepareStatement("select * from add_orphan");
			
			ResultSet rs2=ps.executeQuery();
	*/	
			
			
      out.write("\r\n");
      out.write("\t\t\t\t\t<thead class=\"thead-dark \">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Orphan_home_name\t&nbsp &nbsp </th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Owner_name\t\t\t&nbsp &nbsp </th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>No_of_Orphans\t\t&nbsp &nbsp\t </th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Owner_mobile\t\t&nbsp &nbsp</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Area \t\t\t\t&nbsp &nbsp</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Address \t\t\t&nbsp &nbsp</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
				
			while(rs2.next()){
				String a=rs2.getString(1) ;
				String b=rs2.getString(2) ;
				String d=rs2.getString(4) ;
				String e=rs2.getString(5) ;
				String f=rs2.getString(6) ;
				String g=rs2.getString(7) ;
			
			
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print(a );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print(b );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print(d );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print(e );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print(f );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print(g );
      out.write(" </td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</tr>\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");

				}
				
      out.write("\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 4rt table -->\t<!-- 4rt table -->\t<!-- 4rt table --> \t<!-- 4rt table -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\" id=\"completed\" style=\"display:none;\">\r\n");
      out.write("<h3 align=\"left\" style=\"font-family: 'Kaushan Script', cursive; font-size:30px; color:Yellow;\"><b>COMPLETED REQUESTS</b></h3>\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\r\n");
      out.write("\t<table class=\"table table-secondary table-responsive\">\r\n");
      out.write("\t");
			
	Statement st3=con.createStatement();
	
	ResultSet rs3=st3.executeQuery("select * from  food_details where area='"+area+"' and Status='DELIVERED' and agent_name='"+aname+"' ");
	

			
			
      out.write("\r\n");
      out.write("\t\t\t\t\t<thead class=\"thead-dark \">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Food_Requested Date (YY-MM-DD) &nbsp &nbsp</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>donar_name  &nbsp &nbsp</th> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Food_Requested address &nbsp &nbsp</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>donar_mobile &nbsp &nbsp</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th> pickuptime &nbsp &nbsp</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Orphange Area  &nbsp &nbsp</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Status_Of_Request &nbsp &nbsp</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Accepted_Agent name &nbsp &nbsp</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Accepted_Agent mobile &nbsp &nbsp </th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Delivery_time &nbsp &nbsp</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
				
			while(rs3.next()){
				String j=rs3.getString(10) ;
				String a=rs3.getString(1) ;
				String f=rs3.getString(6) ;
				String h=rs3.getString(8) ;
				String c=rs3.getString(3) ;
				String g=rs3.getString(7) ;			
				String k=rs3.getString(11);
				String l=rs3.getString(12);
				String m=rs3.getString(13);
				String n=rs3.getString(14);
	
			
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(j );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(a );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(f );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(h );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(c );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(g );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td><font color=\"green\"><b>");
      out.print(k );
      out.write("</b></font></td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(l );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(m );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(n );
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</tr>\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");

				}
				
      out.write("\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
